### ISSUE TITLE
There was an error while fetching events!

### ISSUE THREAD

**Issue by Hammer36** [cdaecke/md_fullcalendar#1]
Hi Chris,
I'm currently trying to integrate your plugin. On my local vm box I'm getting a popup message "There was an error while fetching events!". Fullcalendar shows up without any events. Calendarize events are working well in list and detail view of the calendarize plugin. Do you have any hint what the problem could be?
System details: typo3: 9.5.14; calendarize: 5.0.1; md_fullcalendar: 1.1.0
Kind regards,
Rolf

**Comment by cdaecke** [comment]
Did you include the static TypoScript of the extension? If so, could you please post the URL of the ajax request, which is fired when the calendar pages is loaded?

**Comment by Hammer36** [comment]
Yes the static include "Fullcalendar.io for ext:Calendarize (md_fullcalendar) has been included.
The URL is '/index.php?id=198&type=1573738558&storage=87' where 198 is the PID where the plugin was inserted and 87 is the PID of the storage folder with the calendarize events.

**Comment by cdaecke** [comment]
That looks all fine.

What happens if you enter the URL `/index.php?id=198&type=1573738558&storage=87` directly in your browser?

**Comment by Hammer36** [comment]
http://192.168.56.101/cougars/public//index.php?id=198&type=1573738558&storage=87 results in a empty page with "[]". HTML source:
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">[]</pre></body></html>

**Comment by cdaecke** [comment]
Hm, that's strage...

Just to make sure: Do you get the status code 200 for the URL above?

**Comment by Hammer36** [comment]
yes
![Bildschirmfoto 2020-04-20 um 23 32 02](https://user-images.githubusercontent.com/36326828/79801887-3e629000-835f-11ea-9a91-7e2960607852.png)

**Comment by cdaecke** [comment]
As you can see in the [code](https://github.com/cdaecke/md_fullcalendar/blob/113b4caf5a05f89f07b2d9918fa608c5d59ae3d2/Resources/Private/Templates/Cal/Show.html#L60), the error message is thrown, if the ajax request fails.

Are you 100% sure, that the request goes to `http://192.168.56.101/cougars/public//index.php?id=198&type=1573738558&storage=87`?

I am asking, because the [URL](https://github.com/cdaecke/md_fullcalendar/blob/113b4caf5a05f89f07b2d9918fa608c5d59ae3d2/Resources/Private/Templates/Cal/Show.html#L58) in the template is called with `/index.php?...`, so this would result in `http://192.168.56.101/index.php?id=198&type=1573738558&storage=87` which is most probably not correct.

**Comment by Hammer36** [comment]
Solved: I moved my test instance to a Docker/DDEV setup. Now it is working as expected. 
Before my local instance was running on a VM box 6.1 with Ubuntu 18.04 on macOS 10.12. I tried different network settings (NAT network, bridged networking) that didn't solve the problem. 

Thank you for your support!

**Comment by cdaecke** [comment]
Glad to hear, that you solved the issue.

Have fun with the extension!
