### ISSUE TITLE
recursive calendar events pages

### ISSUE THREAD

**Issue by ftrojahn** [cdaecke/md_fullcalendar#16]
In [setup.typoscript](https://github.com/cdaecke/md_fullcalendar/blob/master/Configuration/TypoScript/setup.typoscript#L14) there is a 'persistence.recursive = 1' setting commented out.

During my tests, md_fullcalendar shows events only, if I include all pages with calendarize events directly in the plugin, in record storage page select box. 

Is recursion available (may be I'm doing something wrong) or otherwise planned?

**Comment by cdaecke** [comment]
Since the `$storagePid` is passed to the template which is needed for the ajax call, the `persistence.recursive` doesn't have any effect:

https://github.com/cdaecke/md_fullcalendar/blob/c44926141e8debfd814e4ba12946247204b2dbcd/Classes/Controller/CalController.php#L100-L113

To your question:
No, recursion is not available and not panned.
